### ISSUE TITLE
Webscoket pong message timeout

### ISSUE THREAD

**Issue by hasanparasteh** [Kucoin/kucoin-go-sdk#130] opened 2023-12-14 12:06 UTC
I use web socket just as your documents said. I use `/market/ticker:all` to get a live feed of symbols prices but suddenly the ws closes and I got the below error message.

```
Wait pong message timeout in 10000 ms
```

How can I fix that?

**Comment by iamalanal** [comment] 2024-07-23 14:12
Is the issue solved?

**Comment by ISAAC-XXYYZZ** [comment] 2024-08-12 07:12
This issue could be caused by several factors, such as poor network conditions or messages not being consumed in time, leading to a heartbeat disconnect with the server. Admittedly, there are some design flaws in the current implementation, and we plan to address them in future iterations.

Since this issue has been around for a while, we will close it for now. If you encounter any new problems, please feel free to open a new issue, and I will respond promptly.

**Closed by ISAAC-XXYYZZ** 2024-08-12 07:12 UTC
Labels: help wanted
